### ISSUE TITLE
Enhance README.md

### ISSUE THREAD

**Issue by rohanagarwal94** [imRishabhGupta/dtuguide#10]
The current readme.md is too mainstream.
Points to remember before generating a PR-
Include the screenshots of the app.
Mention the license of the app (MIT).
A short description of each point mentioned already.
Link to the playstore.

**Comment by andreybleme** [comment]
Hey @rohanagarwal94. I can help with this issue, assign it to me :+1:

**Comment by rohanagarwal94** [comment]
@andreybleme yeah sure you can start working on it.

**Comment by andreybleme** [comment]
@rohanagarwal94 could you please assign it?
