### ISSUE TITLE
App isn't responding

### ISSUE THREAD

**Issue by anubhakushwaha** [imRishabhGupta/dtuguide#8]
On clicking Notes under the Navigation Drawer,the app isn't responding.

**Comment by rohanagarwal94** [comment]
@anubhakushwaha could you please post your logcat cause there is no problem as such on the device we are testing on.

**Comment by anubhakushwaha** [comment]
![screenshot_20161013-000118](https://cloud.githubusercontent.com/assets/12814245/19322991/b3812824-90d8-11e6-8438-72e6ca2cb893.png)
This is what happening exactly,will have to look through the code,the logcat says something to do with memory leaks.

**Comment by imRishabhGupta** [comment]
![screenshot_20161012-235033](https://cloud.githubusercontent.com/assets/16560186/19323262/cf604c0e-90d9-11e6-8cce-9caec9d3067b.png)
This is the screenshot from my device. Did you change the link on web view client from DTU Notes to DTU Studies?

**Comment by rohanagarwal94** [comment]
@anubhakushwaha the code needs some refactoring and updating on the remote. @imRishabhGupta will provide the link ASAP. Meanwhile just ignore that activity till its fixed.

**Comment by rohanagarwal94** [comment]
@anubhakushwaha the new changes are uploaded!
